app:
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: true

crawler:
  request_interval: 1000
  enable_crawler: true
  use_proxy: false
  default_proxy: "http://127.0.0.1:10086"

# 推送模式：daily | incremental | current
report:
  mode: "daily"    # 每日汇总模式（一天一份汇总）
  rank_threshold: 5

notification:
  enable_notification: true
  message_batch_size: 4000
  dingtalk_batch_size: 20000
  batch_send_interval: 1
  feishu_message_separator: "━━━━━━━━━━━━━━━━━━━"

  # 开启时间窗口，配合 GitHub Actions 可控制“每天一次”的推送（窗口设为 20:00-22:00）
  push_window:
    enabled: false                 # 开启时间窗口，避免多次推送
    # 注意：GitHub Actions 执行时间不稳定，建议设置 2 小时窗口以保证命中
    time_range:
      start: "20:00"              # 窗口开始（北京时间）
      end: "22:00"                # 窗口结束（北京时间）
    once_per_day: true            # 窗口内只推一次（符合“每天推送”需求）
    push_record_retention_days: 7

  # 请勿在此填写真实凭证（在 GitHub Secrets 中设置）
  webhooks:
    feishu_url: ""
    dingtalk_url: ""
    wework_url: ""
    telegram_bot_token: ""    # 留空 — 使用 GitHub Secrets 注入 TELEGRAM_BOT_TOKEN
    telegram_chat_id: ""      # 留空 — 使用 GitHub Secrets 注入 TELEGRAM_CHAT_ID
    email_from: ""
    email_password: ""
    email_to: ""
    email_smtp_server: ""
    email_smtp_port: ""
    ntfy_server_url: "https://ntfy.sh"
    ntfy_topic: ""
    ntfy_token: ""

weight:
  rank_weight: 0.6
  frequency_weight: 0.3
  hotness_weight: 0.1

platforms:
  - id: "toutiao"
    name: "今日头条"
  - id: "baidu"
    name: "百度热搜"
  - id: "wallstreetcn-hot"
    name: "华尔街见闻"
  - id: "thepaper"
    name: "澎湃新闻"
  - id: "bilibili-hot-search"
    name: "bilibili 热搜"
  - id: "cls-hot"
    name: "财联社热门"
  - id: "ifeng"
    name: "凤凰网"
  - id: "tieba"
    name: "贴吧"
  - id: "weibo"
    name: "微博"
  - id: "douyin"
    name: "抖音"
  - id: "zhihu"
    name: "知乎"
# -------------------
# MCP / LLM 相关配置（启用时会调用第三方 LLM 做摘要/问答/聚类/embeddings）
# 请不要把 key 写到这里。把 key / base / model 放到 GitHub Secrets（见下面步骤）。
# -------------------
mcp:
  enable: true                 # 开启 MCP（做摘要/问答/embeddings 等）
  provider: "openai"          # 使用 OpenAI 兼容接口（也可为 "anthropic" 等，视 repo 支持）
  # 不要在这里直接写密钥或真实 url，留空用 Secrets 注入
  openai_api_key: ""
  openai_api_base: ""         # 例如: https://newapi.520952.xyz
  openai_model: ""            # 例如: v0-1.5-lg

  # MCP 的其它可选项（视 repo 版本支持）
  # max_tokens: 512
  # temperature: 0.2
  # embedding_model: "text-embedding-3-small"

# 其他可选 mcp 配置（各版本字段名字可能略有差异，请确认代码）
# anthropic:
#   anthropic_api_key: ""
#   anthropic_model: ""
